baseURL = "https://sypheos.github.io/lorawan-stack"
languageCode = "en-us"
title = "LoRaWAN Stack"
theme = "hugo-theme-techdoc"

enableGitInfo = true
publishDir = "docs"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]
