baseURL = "http://example.org/"
languageCode = "en-us"
title = "LoRaWAN Stack"
theme = "hugo-theme-techdoc"

enableGitInfo = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]
